
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class StudentGrade extends javax.swing.JFrame {

    /**
     * Creates new form StudentGrade
     */
    static String Id;
    Connection con;
    PreparedStatement pst ;
    ResultSet rs;
    String t, c;
    int y;
    public StudentGrade(String Id) {
        this.Id = Id;
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cms", "root", "root");
            pst = con.prepareStatement("SELECT DISTINCT year FROM grading where cms_id = ?;");
            pst.setString(1, Id);
            rs = pst.executeQuery();
           
            DefaultComboBoxModel yearModel = new DefaultComboBoxModel();
            while(rs.next()) {
                int ye = rs.getInt("year");
                yearModel.addElement(ye + "");
            }
            year.setModel(yearModel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        }

        
        
        
        
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        term = new javax.swing.JComboBox<>();
        course = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        view = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sessional = new javax.swing.JLabel();
        finals = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        grade = new javax.swing.JLabel();
        cgpa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(7, 10, 82));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(1085, 48));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Grades");

        back_btn.setBackground(new java.awt.Color(7, 10, 82));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Term:");

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Year:");

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Course :");

        term.setBackground(new java.awt.Color(255, 255, 255));
        term.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        term.setForeground(new java.awt.Color(7, 10, 82));
        term.setMaximumRowCount(3);
        term.setToolTipText("hello");
        term.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        term.setPreferredSize(new java.awt.Dimension(128, 38));
        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });

        course.setBackground(new java.awt.Color(255, 255, 255));
        course.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        course.setForeground(new java.awt.Color(7, 10, 82));
        course.setMaximumRowCount(3);
        course.setToolTipText("hello");
        course.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        course.setPreferredSize(new java.awt.Dimension(128, 38));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        year.setBackground(new java.awt.Color(255, 255, 255));
        year.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        year.setForeground(new java.awt.Color(7, 10, 82));
        year.setMaximumRowCount(3);
        year.setToolTipText("hello");
        year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        year.setPreferredSize(new java.awt.Dimension(128, 38));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(7, 10, 82));
        view.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View Grade");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 10, 82));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Mid Marks:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 10, 82));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Final Marks:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        mid.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        mid.setForeground(new java.awt.Color(0, 0, 51));
        mid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mid.setText("0");
        mid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(7, 10, 82), 1, true));

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(7, 10, 82));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Sessional Marks:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        sessional.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        sessional.setForeground(new java.awt.Color(7, 10, 82));
        sessional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sessional.setText("0");
        sessional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        finals.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        finals.setForeground(new java.awt.Color(7, 10, 82));
        finals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finals.setText("0");
        finals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        tot.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        tot.setForeground(new java.awt.Color(7, 10, 82));
        tot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tot.setText("0");
        tot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        jLabel15.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 10, 82));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Grade:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        grade.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        grade.setForeground(new java.awt.Color(7, 10, 82));
        grade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grade.setText("F");
        grade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        cgpa.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        cgpa.setForeground(new java.awt.Color(7, 10, 82));
        cgpa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cgpa.setText("Total Marks:");
        cgpa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 10, 82)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cgpa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finals, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sessional, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mid, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessional, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finals, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 278, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            t = term.getSelectedItem().toString();
           
            DefaultComboBoxModel courseModel = new DefaultComboBoxModel();
            //PreparedStatement pst = con.prepareStatement("SELECT DISTINCT sections.course_id, courses.name FROM sections INNER JOIN courses ON sections.course_id = courses.id WHERE ins_id = ?");

            pst = con.prepareStatement("SELECT DISTINCT grading.course_id, courses.name FROM grading INNER JOIN courses ON grading.course_id = courses.id WHERE grading.cms_id = ? and grading.year = ? and grading.term = ?;");
            pst.setString(1, Id);
            pst.setInt(2, y);
            pst.setString(3, t);
            rs = pst.executeQuery();
            while(rs.next()){
                String courseId = rs.getString("course_id");
                String courseName = rs.getString("name");
                courseModel.addElement(courseId + ":" + courseName);
            }
            course.setModel(courseModel);
        } catch (SQLException ex) {
            Logger.getLogger(InstructorAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_termActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
        String courses = course.getSelectedItem().toString();
        String[] courses_arr = courses.split(":");
        c = courses_arr[0];
    }//GEN-LAST:event_courseActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            y = Integer.parseInt(year.getSelectedItem().toString());
           
            DefaultComboBoxModel termModel = new DefaultComboBoxModel();
            pst = con.prepareStatement("SELECT DISTINCT term FROM grading WHERE cms_id = ? and year = ?;");
            pst.setString(1, Id);
            pst.setInt(2, y);
            rs = pst.executeQuery();
            while(rs.next()){
                String term_ = rs.getString("term");
                termModel.addElement(term_);
            }
            term.setModel(termModel);
        } catch (SQLException ex) {
            Logger.getLogger(InstructorAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yearActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        try {
            // TODO add your handling code here:
            pst = con.prepareStatement("SELECT mid_marks, sessionals, final_marks FROM grading WHERE cms_id = ? and year = ? and term = ? and course_id = ?;");
            pst.setString(1, Id);
            pst.setInt(2, y);
            pst.setString(3, t);
            pst.setString(4, c);
            rs = pst.executeQuery();
            while(rs.next()){
                float m = rs.getFloat("mid_marks");
                float s = rs.getFloat("sessionals");
                float f = rs.getFloat("final_marks");
                float total = m + s + f;
                mid.setText(m + "");
                sessional.setText(s + "");
                finals.setText(f + "");
                tot.setText(total + "");
                if(total >= 93)
                    grade.setText("A");
                else if(total >= 87 && total < 92)
                    grade.setText("A-");
                else if(total >= 82 && total < 87)
                    grade.setText("B+");
                else if(total >= 77 && total < 82)
                    grade.setText("B");
                else if(total >= 72 && total < 77)
                    grade.setText("B-");
                else if(total >= 68 && total < 72)
                    grade.setText("C+");
                else if(total >= 64 && total < 68)
                    grade.setText("C");
                else if(total >= 60 && total < 64)
                    grade.setText("C-");
                else
                    grade.setText("F");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentGrade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        new StudentHomePage(Id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrade(Id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel cgpa;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JLabel finals;
    private javax.swing.JLabel grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mid;
    private javax.swing.JLabel sessional;
    private javax.swing.JComboBox<String> term;
    private javax.swing.JLabel tot;
    private javax.swing.JButton view;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
